### ISSUE TITLE
BoxDestroyer - Meebles

### ISSUE THREAD

**Issue by Byrth** [svanheulen/boxdestroyer-windower-addon#4]
From https://github.com/Windower/Issues/issues/679 :

> The chests in Meebles work differently then the standard gold chests:
> They are more like the Abyssea ones where you enter a number each time and then get BOTH a higher or lower based off the number you entered plus a hint about the number. (I haven't checked if the plugin is working on abby gold chests as everyone just keys those anyway.)
> 
> The old BoxHelper plugin was buggy with the meeble chests and would only show the results for one of the two hints but that was still helpful. However, BoxDestroyer doesn't show anything for these chests at all.
> 
> Also, an option to make the suggestions pop up as soon as you get the hint rather than next time you click the chest (like plugin did) would be nice. Thanks!

**Comment by svanheulen** [comment]
Sorry, I would love to help but I don't play the game any more (haven't for a while) so I can't really do any testing :(

**Comment by Byrth** [comment]
The issue is likely just the lack of a messages table entry for those zones. Meebles can take place in Ghoyu's Reverie (129), Everbloom Hollow (86), Ruhotz Silvermines (93). The chest-related minigame may only appear in one of the three zones (Ruhotz Silvermines) based on BG's information.

The issue is that I'm pretty sure POLUtils has the wrong zone for Ruhotz Silvermines. It looks to me like an outside zone. Either way, it lacks the message IDs. Still, that is probably the only problem.

**Comment by svanheulen** [comment]
It's been quite some time since I've done that Meebles so I don't really remember, but from the issue you quoted it sounds like the messages aren't exactly the same. Also if the the caskets are named something other then "Treasure Casket" that will have to be changed in the script as well. I can make whatever changes are needed so long as someone can provide the information since I don't even have the game installed.

What I would need:
1. zone IDs (got that)
2. exact message strings from the DATs (if they're different)
3. casket names from the DATs (if they're different)
4. someone that has the game installed will have to run the make_messages.py script once I've made the changes

**Comment by Byrth** [comment]
Okay. There's a 2 week free login campaign that starts tomorrow morning. I still have the game installed, so I'll give it a shot tomorrow night or so.

**Comment by jambalia** [comment]
yeah mine just gives the first guess and keeps guessing same thing every time 54 or what ever it is
