### ISSUE TITLE
BoxDestroyer

### ISSUE THREAD

**Issue by Feary** [svanheulen/boxdestroyer-windower-addon#5]
doesnt work form latest update, doesnt calculate currently, im guessing something was changed in mem and needs to be re-associated.

**Comment by svanheulen** [comment]
I don't play the game any more so I can't test it. You'll have to give me a some more info if I'm going to be able to help. Are there any error messages at all?

It's possible that the issue is simply that the message IDs changed, in which case you'll have to use the Python script in the "messages" folder to regenerate the "messages.lua" file.

**Comment by semiju** [comment]
I did just this and it is working again.  I'm not very familiar with github though. Is there somewhere I can upload put the updated "messages.lua"?

**Comment by svanheulen** [comment]
Best way is to make a fork of my repo, commit the changes and create a pull request. Or you can just make a Gist (there's a link at the top of the page near the search bar) and give a link to that.
