### ISSUE TITLE
Bad argument #1 to format

### ISSUE THREAD

**Issue by DeaconMidgard** [svanheulen/boxdestroyer-windower-addon#9]
attempting to open new box generates an error and doesn't return anything until after a few attempts and the numbers are incorrect.

Error is boxdestroyer.lua:119: bad argument #1 to format (number expected, got nil)

**Comment by svanheulen** [comment]
The December update must have changed the message IDs again. See #7 for deatails.
Basically you (or someone) needs to generate a new `messages.lua` file. It's fairly easy to do but you need the game installed and fully updated, which I don't since I stopped playing long ago. There's a Python script in the `messages` folder in this repository for doing it and I can walk you through how to run it if you can't figure it out.

**Comment by DeaconMidgard** [comment]
I think I got it. Seems to be working now after testing in a few zones. Had to edit the python script to get it to work on my system. I submitted a pull request with changes. Hope I didn't butcher it as I am not familiar with GitHub.

**Comment by svanheulen** [comment]
Thanks again for doing that. I made a pull request on the Windower Lua repo so it should show up in the official client soon.
